version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - 50051:50051
    container_name: server
    pull_policy: always
    environment:
      - HTTP2_TLS_SERVER_ADDR=0.0.0.0


  client:
    build: 
      context: .
      dockerfile: docker/client/Dockerfile
    container_name: client
    pull_policy: always
    environment:
      - HTTP2_TLS_SERVER_NAME=server
